spin_version = "1"
authors = ["timothy"]
description = ""
name = "challenge-1"
trigger = { type = "http", base = "/" }
version = "0.1.0"

[[component]]
id = "challenge-1"
source = "target/wasm32-wasi/release/challenge_1.wasm"
[component.trigger]
route = "/..."
[component.build]
command = "cargo build --target wasm32-wasi --release"
